name: OSMD BookCab run tests

on:
    push:
      branches: [ main ]

jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.10.8]
       steps:
        - uses: actions/checkout@main
        - name: Initialize Python 3.10.8
          uses: actions/setup-python@v1
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies and run tests
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python -m pytest 
      autoclose:
        steps:
          - name: Issues Auto-close
          - uses: roots/issue-closer@v1.1
            with:
              issue-close-message: "@${issue.user.login} this issue was automatically closed because it did not follow the issue template"
              issue-pattern: ".*guidelines for Contributing.*"